# infrastructure/k8s/base/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: citation-finder
type: Opaque
data:
  # These values need to be base64 encoded
  DB_HOST: "Y2l0YXRpb24tZmluZGVyLWRiLWRvLXVzZXItMTc0MDQwNTYtMC5pLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQ=="
  DB_PORT: "MjUwNjA="
  DB_NAME: "ZGVmYXVsdGRi"
  DB_USER: "ZG9hZG1pbg=="
  DB_PASSWORD: "QVZOU18zelM1TENnZmJKNGZrNHk3YTFv"
  DB_SSL_MODE: "cmVxdWlyZQ=="

# Add to your existing database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: citation-finder
type: Opaque
data:
  PUBMED_API_KEY: "OWI4N2VjNDM3YWY4M2YyZDA2MGIyNzY5NWQ3MGQ2YTc1YTA4"
