apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
  namespace: citation-finder
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 8000        # Changed to match the container port
      targetPort: 8000  # Port the container is listening on
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  namespace: citation-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      imagePullSecrets:
      - name: citation-finder
      containers:
      - name: data-ingestion
        image: registry.digitalocean.com/citation-finder/data-ingestion:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_SSL_MODE
        - name: PUBMED_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: PUBMED_API_KEY