# infrastructure/k8s/base/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: citation-finder
type: Opaque
data:
  # These values need to be base64 encoded
  DB_HOST: "Y2l0YXRpb24tZmluZGVyLWRiLWRvLXVzZXItMTc0MDQwNTYtMC5pLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQ=="
  DB_PORT: "MjUwNjA="
  DB_NAME: "ZGVmYXVsdGRi"
  DB_USER: "ZG9hZG1pbg=="
  DB_PASSWORD: "QVZOUl8zelM1TENnZmJKNGZrNHk3YTFv"
  DB_SSL_MODE: "cmVxdWlyZQ=="
