# infrastructure/k8s/base/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: citation-finder
type: Opaque
data:
  # These values need to be base64 encoded
  DB_HOST: 
  DB_PORT: 
  DB_NAME: 
  DB_USER: 
  DB_PASSWORD: 
  DB_SSL_MODE: 

# Add to your existing database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: citation-finder
type: Opaque
data:
  PUBMED_API_KEY: 
