apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: citation-finder-ingress
  namespace: citation-finder
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.citation-finder.com
    http:
      paths:
      - path: /api/v1/ingest
        pathType: Prefix
        backend:
          service:
            name: data-ingestion
            port:
              number: 8000