"""Initial migration

Revision ID: 84d614be7052
Revises: 
Create Date: 2024-12-02 23:52:21.864189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d614be7052'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=True)
    op.create_table('citations',
    sa.Column('citing_paper_id', sa.Integer(), nullable=False),
    sa.Column('cited_paper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('citing_paper_id', 'cited_paper_id')
    )
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_authors')
    op.drop_table('citations')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('authors')
    # ### end Alembic commands ###
