"""Initial schema with citations

Revision ID: cda1ea52eeb3
Revises: 
Create Date: 2024-12-06 02:18:06.289876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda1ea52eeb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_citations',
    sa.Column('citing_paper_id', sa.Integer(), nullable=True),
    sa.Column('cited_paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_citations')
    # ### end Alembic commands ###
